#!/bin/bash
#
# vim ft: shell

set -eu -o pipefail

[ "${DEBUG:=false}" = "true" ] && set -x

print_info() {
    printf "[\033[1;35m+\033[0m] INFO: %s\n" "${1}"
}

print_warn() {
    printf "[\033[1;33m!\033[0m] \033[1;33mWARNING\033[0m: %s\n" "${1}" >&2
}

print_error() {
    printf "[\033[1;34mx\033[0m] \033[1;34mERROR\033[0m: %s\n" "${1}" >&2
    exit 1
}

print_usage() {
    cat <<HEREDOC >&2

  usage: $(basename "${0}") [-qh] OUTPUT_DIR

    -q, --quiet         Do not output to stdout
    -h, --help          Print this help and exit

HEREDOC
}

_makerepo() {
    output_dir="${1?Missing output dir parameter}"

    print_info "Generating package indexes"

    mkdir -p "$output_dir"/{sources,packages}

    (
    shopt -s globstar nullglob
    cp -v ./**/{*.dsc,*.orig.tar*,*.debian.tar*} "$output_dir"/sources
    cp -v ./**/*.deb "$output_dir"/packages
    )

    # Generate package indexes
    ( cd "$output_dir"; dpkg-scanpackages packages/ | gzip -9c > packages/Packages.gz )
    ( cd "$output_dir"; dpkg-scansources sources/ | gzip -9c > sources/Sources.gz )
}

while true; do
    shiftpos=2

    case "${1:-}" in
        -q|--quiet)
            exec >> /dev/null
            shiftpos=1
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        *) break ;;
    esac

    shift "$shiftpos"
done

_makerepo "$@"
