#!/bin/bash
#
# vim ft: shell

set -eu -o pipefail

[ "${DEBUG:=false}" = "true" ] && set -x

print_info() {
    printf "[\033[1;35m+\033[0m] INFO: %s\n" "${1}"
}

print_usage() {
    cat <<HEREDOC >&2

  usage: $(basename "${0}") [-sqh]

    -s, --source        Only fetch sources and exit
    -q, --quiet         Do not output to stdout
    -h, --help          Print this help and exit

HEREDOC
}

checksum() {
    echo "$1 $2" | sha256sum -c - 2>/dev/null
}

fetch_dist() {

    print_info "Fetching sources for '$pkgname'"

    dist_file="dist/${dist##*/}"
    mkdir -p dist

    if ! checksum "${dist_sha256}" "${dist_file}"; then
        curl -sSfL -o "${dist_file}" "${dist}"
        checksum "${dist_sha256}" "${dist_file}"
    fi

    if tar -tf "${dist_file}" >/dev/null 2>&1; then
        tar -xf "${dist_file}" --strip 1 -C "${source_dir}"
    else
        cp "${dist_file}" "${source_dir}"/
    fi

}

fetch_sources() {
    (
    # shellcheck source=example-package/hello-world/pkg.conf
    source pkg.conf

    source_dir="${pkgname}-${pkgver}"

    rm -rf "${source_dir}"
    mkdir "${source_dir}"

    if [ -n "${dist:-}" ]; then
        fetch_dist
    else
        print_info "No dist file for '$pkgname'"
    fi

    orig="${pkgname}_${pkgver}.orig.tar.gz"
    tar -czf "$orig" --recursive "${source_dir}"

    cp -r debian "${source_dir}"/
    )
}

_makepkg() {(
    fetch_sources

    case "${1:-}" in
        -s|-S|--source)
            return
            ;;
    esac

    # Refresh package index for build dependencies
    sudo apt-get update

    # shellcheck source=example-package/hello-world/pkg.conf
    source pkg.conf

    pushd "${pkgname}-${pkgver}"

    print_info "Building package '$pkgname'"

    # Get build deps for package
    sudo apt-get build-dep -y .

    debuild -- clean 2>&1
    # Source package
    debuild --no-lintian -S -uc -us 2>&1
    # Binary package
    debuild --no-lintian -b -uc -us 2>&1

    debuild -- clean 2>&1
)}

while true; do
    shiftpos=2

    case "${1:-}" in
        -q|--quiet)
            exec >> /dev/null
            shiftpos=1
            ;;
        -h|--help)
            print_usage
            exit 0
            ;;
        *) break ;;
    esac

    shift "$shiftpos"
done

_makepkg "$@"
