#!/bin/bash
#
# vim ft: shell

set -eu -o pipefail

[ "${DEBUG:=false}" = "true" ] && set -x

print_info() {
    printf "[\033[1;35m+\033[0m] INFO: %s\n" "${1}"
}

print_warn() {
    printf "[\033[1;33m!\033[0m] \033[1;33mWARNING\033[0m: %s\n" "${1}" >&2
}

print_error() {
    printf "[\033[1;34mx\033[0m] \033[1;34mERROR\033[0m: %s\n" "${1}" >&2
    exit 1
}

_updpkgsum() {

    # shellcheck source=example-package/hello-world/pkg.conf
    source pkg.conf

    print_info "Checking checksum for '$pkgname'"

    dist_file="${dist##*/}"

    curl -sSfL -o "${dist_file}" "${dist}"

    checksum=$(sha256sum "${dist_file}" | cut -d' ' -f1)

    # Return if sum is unchanged
    [ "${checksum}" = "${dist_sha256}" ] && return

    print_info "Updating checksum for '$pkgname'"

    sed -Ei "s|^(dist_sha256=)[[:alnum:]].+$|\1${checksum}|" pkg.conf
}

_updpkgsum "$@"
